### ISSUE TITLE
Arch Package squashfuse-0.3.0 breaks appimages..

### ISSUE THREAD

**Issue by Theslees** [vasi/squashfuse#105] opened 2023-07-27 21:34 UTC
```
[0] arch-desktop:Downloads joey$ ./linux−Miru−4.2.8.AppImage
QSocketNotifier: Can only be used with threads started with QThread
Segmentationfault(coredumped)
[139] arch-desktop:Downloads joey$ 
```
I upgraded squashfuse via a system package upgrade (with the arch system repository, dont know which one specific repository the package comes from though), then after that, all appimages failed to run,

It spits out the shell log posted above everytime I attempt to execute a appimage

So I reverted back to squashfuse v0.2.0 and appimages work again, I don't know much about squashfuse itself but it seems the latest update (0.3.0) caused a regression for appimages on my system; I'm on Arch Linux btw,

Please let me know if you can replicate the issue on your side aswell, Cheers.

**Comment by DrDaveD** [comment] 2023-07-27 21:50
I'm not very familiar with Arch Linux so it would be a big help if you can dig deeper into finding out the cause of the failure and hopefully submit a pull request.

**Comment by maoxuner** [comment] 2023-07-28 01:57
> Check `journalctl`, is it constantly segfaulting like this ever since the upgrade? I downgraded as soon as I saw it so didnt actually try appimages, but i assume its related.
> 
> You can use `pacman -U https://archive.archlinux.org/packages/s/squashfuse/squashfuse-0.2.0-1-x86_64.pkg.tar.zst` to downgrade temporarily
> 
> journalctl snippet

downgrade to 0.2.0 works

**Comment by lgdsgd2000** [comment] 2023-07-28 02:49
> 

Yes, there is indeed such segfaulting and downgrade to 0.2.0 works

**Comment by palexdev** [comment] 2023-07-28 12:15
This is critical, we have work to do you know

**Comment by DrDaveD** [comment] 2023-07-28 13:31
That's the danger of living on the bleeding edge.

Another workaround besides downgrading to 0.2.0 would be to use the `--disable-multithreading` configure option, but then of course you don't get the multithreading benefit.

**Comment by tysontan** [comment] 2023-07-28 13:51
> Check `journalctl`, is it constantly segfaulting like this ever since the upgrade? I downgraded as soon as I saw it so didnt actually try appimages, but i assume its related.
> 
> You can use `pacman -U https://archive.archlinux.org/packages/s/squashfuse/squashfuse-0.2.0-1-x86_64.pkg.tar.zst` to downgrade temporarily
> journalctl snippet

Thanks for the workaround!

**Comment by Snynth** [comment] 2023-07-29 01:21
Downgrading to 0.2.0 worked as a workaround.

**Comment by maoxuner** [comment] 2023-07-29 01:49
> That's the danger of living on the bleeding edge.
> 
> Another workaround besides downgrading to 0.2.0 would be to use the `--disable-multithreading` configure option, but then of course you don't get the multithreading benefit.

Assumming that all packages are basically tested in `testing` repository, then come into production. Should not blame for bleeding edge, it just not tested.

**Comment by purpasmart96** [comment] 2023-07-29 07:03
Confirmed on my side also, downgrading back to 2.0 fixed all the appimages.

**Comment by max8rr8** [comment] 2023-07-29 13:48
This problem appeared in 53e1b97002c7bc13392a6b0121680d28a94a9715 when signatures of functions such as `sqfs_lookup_path` and `sqfs_open_image` got changed (new function argument added). Libappimage(both upstream and in arch repository) is compiled with squashfuse v0.2 uses old signatures which leads to segfault. 

The fact that there is no way to differentiate between old and new functions signatures with c preprocessor further complicates issue as libappimage(and other projects using squashfuse). I would suggest adding 
```c
#define SQUASHFUSE_SUBDIR
``` 
Or something similar(or even better an integer indicating current version) so projects using squashfuse would be able to use correct function signatures whether compiling against older or newer versions of squashfuse. 

Another possible solution is to change 53e1b97002c7bc13392a6b0121680d28a94a9715 so instead of modifying existing functions it will create new ones (with suffix `_with_subdir` f.e.)

**Comment by DrDaveD** [comment] 2023-07-29 14:25
Oh, so the problem was the subdir feature, not the multithreading.

Please submit a pull request with suggested fix.

**Comment by max8rr8** [comment] 2023-07-29 15:19
> Please submit a pull request with suggested fix.

I am not sure which fix is better:
1. Provide squash fs version with defines
  ```c
  #define SQUASHFUSE_MAJOR_VERSION 0
  #define SQUASHFUSE_MINOR_VERSION 0
  ```
2. Add define that shows that subdir signature should be used
  ```c
  #define SQUASHFUSE_SUBDIR_SUPPORTED
  ```
3. Restore old signatures and add subdir support in functions with new names

**Comment by kevin-vigor** [comment] 2023-07-29 16:02
Fwiw I vote for option 3. It requires no changes to existing apps.

**Comment by hsdredgun** [comment] 2023-07-29 23:42
I'm confused I removed the Aur package of Appimagelauncher then downgrade to 2.0 and now I can't install appimagelauncher again unfortunately:

`[ 76%] Linking CXX shared library libbinfmt-bypass-preload.so
/home/hsdredgun/.cache/yay/appimagelauncher-git/src/AppImageLauncher/src/binfmt-bypass/fix-preload-library.sh: line 26: patchelf: command not found
make[2]: *** [src/binfmt-bypass/CMakeFiles/binfmt-bypass-preload.dir/build.make:114: src/binfmt-bypass/libbinfmt-bypass-preload.so] Error 127
make[2]: *** Deleting file 'src/binfmt-bypass/libbinfmt-bypass-preload.so'
make[1]: *** [CMakeFiles/Makefile2:1850: src/binfmt-bypass/CMakeFiles/binfmt-bypass-preload.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: appimagelauncher-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
appimagelauncher-git - exit status 4`

Sorry very new to this...

**Comment by vasi** [comment] 2023-07-30 00:37
Yeah, I agree with @kevin-vigor

**Comment by max8rr8** [comment] 2023-07-30 07:55
Fixed by #106

**Closed** 2023-07-30 08:16 UTC

**Comment by Porpoise1954** [comment] 2023-12-12 12:07
I'm having this issue on **Linux Mint 21.2 Victoria (Cinnamon).**
squashfuse is v.0.1.103-3

When I downloaded "/home/*****/Applications/**appimagelauncher-lite-2.2.0-travis995-0f91801-x86_64.AppImage**" it would not launch. However, **DigiKam-8.1.0-x86-64.Appimage** still works, as does **kmymoney-5.1-607-linux-gcc-x86_64.Appimage** and  **CinGG-20230630-x86_64_c99375297a357e6bc0cbd1239af8903d.AppImage** but  **XnView_MP.glibc2.17-x86_64.Appimage** no longer works.

Can anyone shed some light please?

**Comment by vasi** [comment] 2023-12-12 12:12
Could you provide logs, or a backtrace? Can't diagnose without more info.
